
###

GET http://localhost:3000/post

###

GET http://localhost:3000/post?sender=Mevorah

###

GET http://localhost:3000/post/67485928b2d6382e78f97e3f

###

POST http://localhost:3000/post
Content-Type: application/json

{
    "sender": "Mevorah",
    "title": "Post 1",
    "content": "HEY!!"
}

###

PUT http://localhost:3000/post/67485928b2d6382e78f97e3f
Content-Type: application/json

{
    "sender": "Mevorah 1234",
    "title": "Post 1234",
    "content": "HEY 1234!!"
}

###

POST http://localhost:3000/comment
Content-Type: application/json

{
    "postId": "67485928b2d6382e78f97e3f",
    "sender": "Tal",
    "content": "HELLO COMMENT!!"
}

###

PUT http://localhost:3000/comment/674fc2b1ce5438cced3236f2
Content-Type: application/json

{
    "sender": "Tal 1234",
    "content": "HELLO COMMENT 1234!!"
}

###

GET http://localhost:3000/comment/post/67485928b2d6382e78f97e3f
Content-Type: application/json

