
###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?owner=Mevorah

###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "owner": "Mevorah",
    "title": "Post 1",
    "content": "This is my first post"
}


###

