
###

GET http://localhost:3000/post

###

GET http://localhost:3000/post?sender=Mevorah

###

GET http://localhost:3000/post/6755df72fa7704d85baec0c2

###

POST http://localhost:3000/post
Content-Type: application/json

{
    "sender": "Mevorah",
    "title": "Post 1",
    "content": "HEY!!"
}

###

PUT http://localhost:3000/post/6755da8614e9b89cb0e24bd4
Content-Type: application/json

{
    "sender": "Mevorah 1234",
    "title": "Post 1234",
    "content": "HEY 1234!!"
}

###

POST http://localhost:3000/comment
Content-Type: application/json

{
    "postId": "6755df72fa7704d85baec0c2",
    "sender": "Tal",
    "content": "HELLO COMMENT!!"
}

###

PUT http://localhost:3000/comment/6755da8614e9b89cb0e24bd4
Content-Type: application/json

{
    "sender": "Tal 1234",
    "content": "HELLO COMMENT 1234!!"
}

###

GET http://localhost:3000/comment/post/6755df72fa7704d85baec0c2
Content-Type: application/json

###

DELETE http://localhost:3000/comment/6755e02efa7704d85baec0ce

###